Download classification dataset:

https://archive.ics.uci.edu/dataset/53/iris


Data definition, from iris.names:

7. Attribute Information:
   1. sepal length in cm (sepal_length)
   2. sepal width in cm (sepal_width)
   3. petal length in cm (petal_length)
   4. petal width in cm (petal_width)
   5. class: ==> class
      -- Iris Setosa
      -- Iris Versicolour
      -- Iris Virginica


In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split


In [3]:
column_names=["sepal_length", "sepal_width", "petal_length", "petal_width", "species"]
data = pd.read_csv('data/iris.data', names=column_names)

# make species a categorical column
data['species'] = data['species'].astype('category')

X = data.drop(["species"], axis=1) 
y = pd.get_dummies(data["species"], dtype=int)


Let's make sure the shapes are what we expected:

In [4]:
assert(X.shape == (150,4))
assert(y.shape == (150,3))

Let's look at the input data

In [5]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [6]:
# y now has evenly-divided categories -- one of each type
y.value_counts()

Iris-setosa  Iris-versicolor  Iris-virginica
0            0                1                 50
             1                0                 50
1            0                0                 50
Name: count, dtype: int64

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) 

Size of inputs
20% are reserved for testing


In [8]:
print("total number of examples   ", len(X))
print("number of training examples", len(X_train))
print("number of test examples    ", len(X_test))

total number of examples    150
number of training examples 120
number of test examples     30


Sample training data


In [9]:
print("** X_train info")
X_train.info()

print("\n** X_train values[0]")
print(X_train.values[0])

print("]\n** y info")
y_train.info()


** X_train info
<class 'pandas.core.frame.DataFrame'>
Index: 120 entries, 22 to 102
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  120 non-null    float64
 1   sepal_width   120 non-null    float64
 2   petal_length  120 non-null    float64
 3   petal_width   120 non-null    float64
dtypes: float64(4)
memory usage: 4.7 KB

** X_train values[0]
[4.6 3.6 1.  0.2]
]
** y info
<class 'pandas.core.frame.DataFrame'>
Index: 120 entries, 22 to 102
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Iris-setosa      120 non-null    int64
 1   Iris-versicolor  120 non-null    int64
 2   Iris-virginica   120 non-null    int64
dtypes: int64(3)
memory usage: 3.8 KB


In [10]:
print(f'X_train: {X_train}')

X_train:      sepal_length  sepal_width  petal_length  petal_width
22            4.6          3.6           1.0          0.2
15            5.7          4.4           1.5          0.4
65            6.7          3.1           4.4          1.4
11            4.8          3.4           1.6          0.2
42            4.4          3.2           1.3          0.2
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[120 rows x 4 columns]


In [11]:
from micrograd.engine import Value
from micrograd.nn import Neuron, Layer, MLP

In [12]:
model = MLP(4, [8, 8, 3]) # 2-layer neural network
print(model)
print("number of parameters", len(model.parameters()))

Multi-Layer Perceptron Structure:
 Layer 1/3 - Shape of the layer is: 4 X 8 (nin X nout)
	[Neuron 0: ReLUNeuron(4) -> w0 = 0.0525, w1 =-0.4929, w2 =-0.3280, w3 = 0.7520, b = 0.0000 ... Neuron 7: ReLUNeuron(4) -> w0 = 0.9004, w1 =-0.1988, w2 =-0.5538, w3 = 0.7177, b = 0.0000]
 Layer 2/3 - Shape of the layer is: 8 X 8 (nin X nout)
	[Neuron 0: ReLUNeuron(8) -> w0 =-0.5417, w1 = 0.1483, w2 = 0.9289, w3 = 0.4005, w4 = 0.0408, w5 = 0.0902, w6 =-0.0183, w7 = 0.4702, b = 0.0000 ... Neuron 7: ReLUNeuron(8) -> w0 = 0.1848, w1 = 0.3491, w2 =-0.2943, w3 = 0.9914, w4 = 0.3657, w5 = 0.8193, w6 = 0.9257, w7 =-0.4127, b = 0.0000]
 Layer 3/3 - Shape of the layer is: 8 X 3 (nin X nout)
	[Neuron 0: LinearNeuron(8) -> w0 =-0.0733, w1 =-0.1654, w2 =-0.7217, w3 =-0.9738, w4 =-0.5723, w5 = 0.7613, w6 = 0.6995, w7 =-0.6142, b = 0.0000 ... Neuron 2: LinearNeuron(8) -> w0 =-0.3792, w1 = 0.3647, w2 =-0.5903, w3 =-0.2290, w4 =-0.2253, w5 = 0.7229, w6 = 0.1927, w7 =-0.1202, b = 0.0000]

number of parameters 139


In [13]:
import random
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [14]:
import math 

def softmax(z):  
    """ Softmax converts a vector of values to a probability distribution.
    Args:
      z (ndarray (N,))  : input data, N features
    Returns:
      a (ndarray (N,))  : softmax of z
    """    
    ### START CODE HERE ### 
    l = np.array(z)
    e_pow_z = math.e**l
    e_pow_z_sum = np.sum(e_pow_z)
    a = e_pow_z / e_pow_z_sum
    return a


In [15]:
def sparse_categorical_crossentropy(y_true, y_pred):
    """
    Calculates the sparse categorical cross-entropy loss.

    Args:
        y_true: Array of one-hot encoded true labels of shape 3xlen(y_pred).
        y_pred: Array of predicted probabilities (2D array).

    Returns:
        float: The calculated loss.
    """
    assert y_true.shape == (120, 3)
    assert y_pred.shape == (120, 3)
        
    print(f'y_pred , {y_pred}')
    print(f'y_true: {y_true}')
    
    log = np.log(y_pred)
    print(f'log: {log}')
    
    mul = y_true * log
    print(f'mul: {mul}')
    
    loss = -1/len(y_true) * np.nansum(np.nansum(y_true * np.log(y_pred)))

    # print the loss
    #print(loss)
    # print("y_pred ", y_pred)
    # print(f'shape: {y_pred.shape}')
    # print(f'y_true: {y_true}')
    # mul = y_true * np.log(y_pred)
    # print(f'mul: {mul}')
    # sum = np.sum(mul, axis=-1)
    # print(f'sum: {sum}')
    # loss = -np.mean(sum)
    # print(f'loss: {loss}')
    return loss

In [16]:
X_train_np = X_train.values
y_train_np = y_train.values

assert X_train_np.shape == (120, 4)
assert y_train_np.shape == (120, 3)

print(f'X_train_np: {X_train_np}')

X_train_np: [[4.6 3.6 1.  0.2]
 [5.7 4.4 1.5 0.4]
 [6.7 3.1 4.4 1.4]
 [4.8 3.4 1.6 0.2]
 [4.4 3.2 1.3 0.2]
 [6.3 2.5 5.  1.9]
 [6.4 3.2 4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.2 4.1 1.5 0.1]
 [5.8 2.7 5.1 1.9]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [5.4 3.9 1.3 0.4]
 [5.4 3.7 1.5 0.2]
 [5.5 2.4 3.7 1. ]
 [6.3 2.8 5.1 1.5]
 [6.4 3.1 5.5 1.8]
 [6.6 3.  4.4 1.4]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [7.6 3.  6.6 2.1]
 [5.6 3.  4.5 1.5]
 [5.1 3.5 1.4 0.2]
 [7.7 2.8 6.7 2. ]
 [5.8 2.7 4.1 1. ]
 [5.2 3.4 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.1 3.8 1.9 0.4]
 [5.  2.  3.5 1. ]
 [6.3 2.7 4.9 1.8]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.1 3.3 1.7 0.5]
 [5.6 2.7 4.2 1.3]
 [5.1 3.4 1.5 0.2]
 [5.7 3.  4.2 1.2]
 [7.7 3.8 6.7 2.2]
 [4.6 3.2 1.4 0.2]
 [6.2 2.9 4.3 1.3]
 [5.7 2.5 5.  2. ]
 [5.5 4.2 1.4 0.2]
 [6.  3.  4.8 1.8]
 [5.8 2.7 5.1 1.9]
 [6.  2.2 4.  1. ]
 [5.4 3.  4.5 1.5]
 [6.2 3.4 5.4 2.3]
 [5.5 2.3 4.  1.3]
 [5.4 3.9 1.7 0.4]
 [5.  2.3 3.3 1. ]
 [6.4 2.7 5.3 1.9]
 [5.  3.3 1.4 0.2]


In [19]:
# loss function
def loss(batch_size=None):

    # inline DataLoader :)
    if batch_size is None:
        Xb, yb = X_train_np, y_train_np
    else:
        ri = np.random.permutation(X.shape[0])[:batch_size]
        Xb, yb = X_train_np[ri], y_train_np[ri]
    inputs = [list(map(Value, xrow)) for xrow in Xb]
    #print("Xb:", Xb[:1], "inputs:", inputs[:1])
    
    # forward the model to get scores
    scores = list(map(model, inputs))
    print(f'scores: {scores}')
    #print("***************************************")
    def get_data(v):
        return [value.data for value in v]
    
    raw_scores = np.array(list(map(get_data, scores)))
    #print(f'raw_scores: {raw_scores}')
    #print('eaw_scores: ',raw_scores[0])
    #print("yb: ", yb, " scores: ", scores)
    data_loss = sparse_categorical_crossentropy(yb, raw_scores)
    #print(f'data_loss: {data_loss}')
    #data_loss = sum(losses) * (1.0 / len(losses))
    # L2 regularization
    alpha = 1e-4
    reg_loss = alpha * sum((p*p for p in model.parameters()))
    #print(f'reg_loss: {reg_loss}')
    total_loss = data_loss + reg_loss
    
    # also get accuracy
    accuracy = [yi ==  np.argmax(softmax(scores)) for yi, scores in zip(yb, raw_scores)]
    return total_loss, sum(accuracy) / len(accuracy)

total_loss, acc = loss()
print("initial total_loss: ", total_loss, " activation: ", acc)

scores: [[Value(data=-2.677497883374307, grad=0), Value(data=0.8107449663006122, grad=0), Value(data=-1.7897170322679492, grad=0)], [Value(data=-3.298854673324202, grad=0), Value(data=1.021727252042018, grad=0), Value(data=-2.17409298393403, grad=0)], [Value(data=-3.604236605128159, grad=0), Value(data=1.3982990720490778, grad=0), Value(data=-1.8058680731856906, grad=0)], [Value(data=-2.969660685713311, grad=0), Value(data=0.9836170729579939, grad=0), Value(data=-1.765128611210615, grad=0)], [Value(data=-2.657232380909992, grad=0), Value(data=0.8507963882968956, grad=0), Value(data=-1.651137709412744, grad=0)], [Value(data=-2.760923322543854, grad=0), Value(data=1.3158350505830536, grad=0), Value(data=-1.1098997873003986, grad=0)], [Value(data=-3.33937354893804, grad=0), Value(data=1.4127541241955663, grad=0), Value(data=-1.542178123585518, grad=0)], [Value(data=-3.125618908338482, grad=0), Value(data=0.9621228773132129, grad=0), Value(data=-1.9743020270466152, grad=0)], [Value(data=-3

/var/folders/_k/cq4d67l51tbcs72vqw3431xc0000gn/T/ipykernel_86126/2816620951.py:18: RuntimeWarning: invalid value encountered in log
  log = np.log(y_pred)
/var/folders/_k/cq4d67l51tbcs72vqw3431xc0000gn/T/ipykernel_86126/2816620951.py:24: RuntimeWarning: invalid value encountered in log
  loss = -1/len(y_true) * np.nansum(np.nansum(y_true * np.log(y_pred)))


In [18]:
# optimization
for k in range(1):
    
    # forward
    total_loss, acc = loss()
    
    # backward
    model.zero_grad()
    total_loss.backward()
    
    # update (sgd)
    learning_rate = 5.0 - 0.9*k/100    
    for p in model.parameters():
        p.data -= learning_rate * p.grad
    
    if k % 5 == 0:
        print(f"step {k} loss {total_loss.data}, accuracy {acc*100}%")


y_pred , [[-2.68554647  0.81318207 -1.79509694]
 [-3.30877106  1.02479857 -2.18062833]
 [-3.61507098  1.40250237 -1.81129653]
 [-2.97858752  0.98657384 -1.77043461]
 [-2.66522005  0.85335389 -1.65610105]
 [-2.76922269  1.31979046 -1.11323616]
 [-3.34941174  1.41700088 -1.54681393]
 [-3.13501455  0.96501503 -1.9802368 ]
 [-3.0162214   0.94836345 -1.8995123 ]
 [-3.26514036  1.10450045 -1.93599866]
 [-2.30581765  1.2580229  -0.87326773]
 [-3.03391415  1.39666741 -1.30923955]
 [-3.50188365  1.46870221 -1.60712604]
 [-3.04883548  0.8763963  -2.11099723]
 [-3.24624585  0.99603107 -2.06467995]
 [-3.02925153  1.22176545 -1.40532696]
 [-3.01640296  1.48971424 -1.12743615]
 [-2.78883589  1.4743115  -1.05159721]
 [-3.52496273  1.38787755 -1.73632406]
 [-2.92089555  1.52200074 -1.19709562]
 [-2.99315761  1.35396317 -1.24246058]
 [-3.21566606  1.71692397 -1.11540294]
 [-2.66555753  1.31046942 -1.08521716]
 [-3.05234582  0.93121968 -1.95413296]
 [-3.29481262  1.76021661 -1.09578753]
 [-3.24379717  1

/var/folders/_k/cq4d67l51tbcs72vqw3431xc0000gn/T/ipykernel_86126/2816620951.py:18: RuntimeWarning: invalid value encountered in log
  log = np.log(y_pred)
/var/folders/_k/cq4d67l51tbcs72vqw3431xc0000gn/T/ipykernel_86126/2816620951.py:24: RuntimeWarning: invalid value encountered in log
  loss = -1/len(y_true) * np.nansum(np.nansum(y_true * np.log(y_pred)))
